version: "3"

volumes:
  mysql_data:
  node_data:

services: 

  app:
    build:
      dockerfile: Dockerfile
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks: 
      - node-network
    volumes:
      - type: volume
        target: /usr/src/app
        source: node_data    
    tty: true
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - type: volume
        target: /var/lib/mysql
        source: mysql_data  
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks: 
  node-network:
    driver: bridge